### ISSUE TITLE
infografía gestion de proyectos  

### ISSUE THREAD

**Issue by AmilkarVladimiR** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-AmilkarVladimiR#1]
[infografia de proyectos de sofware_Vladimir .pdf](https://github.com/user-attachments/files/16785395/infografia.de.proyectos.de.sofware_Vladimir.pdf)

**Comment by saul19bautista** [comment]
ENTENDIBLE Y BIEN DESARROLLADO 
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
